### ISSUE TITLE
SegNet is not working with more than three bands because of using VGG16 pretrained weights

### ISSUE THREAD

**Issue by shubhawasthi123** [venkanna37/Label-Pixels#8]
Using TensorFlow backend.
Traceback (most recent call last):
  File "train.py", line 63, in <module>
    train(args)
  File "train.py", line 20, in train
    model = lu.select_model(args)
  File "/home/user/Downloads/Label-Pixels/tools/models/lp_utils.py", line 23, in select_model
    model = segnet_model.create_segnet(args)
  File "/home/user/Downloads/Label-Pixels/tools/models/segnet_model.py", line 158, in create_segnet
    encoder = VGG16_encoder(input_shape, init=True)
  File "/home/user/Downloads/Label-Pixels/tools/models/segnet_model.py", line 80, in VGG16_encoder
    weights_fname = write_new_VGG_weights(input_shape, weights_fname, outfname)
  File "/home/user/Downloads/Label-Pixels/tools/models/segnet_model.py", line 67, in write_new_VGG_weights
    del f["block1_conv1"]["block1_conv1_W_1:0"]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/user/anaconda3/envs/label-pixels/lib/python3.6/site-packages/h5py/_hl/group.py", line 264, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'block1_conv1' doesn't exist)"

**Comment by venkanna37** [comment]
Removed this feature to load the pre-trained model in the SegNet encoder. This option will be added later. Closing this issue for now.
